CREATE TABLE USER_INFO 
(
  USER_ID NUMBER(5) 
, USER_NAME VARCHAR2(20) 
, USER_EMAIL VARCHAR2(20) 
);

COMMENT ON COLUMN USER_INFO.USER_ID IS '저장된 순서';

COMMENT ON COLUMN USER_INFO.USER_NAME IS '사용자 이름';

COMMENT ON COLUMN USER_INFO.USER_EMAIL IS '사용자 이메일';
